In [4]:
import pdfplumber
import os
import pandas as pd
import re

In [5]:
def year_month_key(filename):
    year, month = map(int, re.search(r"Summary_(\d+)_(\d+)_", filename).groups())
    return year, month

def merge_pdfs_to_single_txt(source_folder, output_txt_name):

    file_names = [x for x in os.listdir("Reports") if x.startswith("Summary_")]
    file_names = sorted(file_names, key=year_month_key)

    global df 

    df = pd.DataFrame(columns = ["ReportName", "Text"])
    index = 0

    for file_name in file_names:
        pdf_path = os.path.join(source_folder, file_name)
        
        try:
            with pdfplumber.open(pdf_path) as pdf:
                file_content = []
                for page in pdf.pages:
                    text = page.extract_text()
                    if text:
                        file_content.append(text)
                single_doc_text = "\n".join(file_content)
                df.loc[index] = [file_name, single_doc_text]
                index+=1
                print(f"Okundu: {file_name}")
                
        except Exception as e:
            print(f"Hata oluştu ({file_name}): {e}")

    df.to_excel("1_SummaryReportsV1.xlsx")
    print(f"\nBütün işlemler tamamlandı! Dosya konumu: {output_txt_name}")

merge_pdfs_to_single_txt("Reports", "Tum_Raporlar.txt")

Okundu: Summary_2006_1_January.pdf
Okundu: Summary_2006_2_February.pdf
Okundu: Summary_2006_3_March.pdf
Okundu: Summary_2006_4_April.pdf
Okundu: Summary_2006_5_May.pdf
Okundu: Summary_2006_6_June.pdf
Okundu: Summary_2006_7_June.pdf
Okundu: Summary_2006_8_July.pdf
Okundu: Summary_2006_9_August.pdf
Okundu: Summary_2006_10_September.pdf
Okundu: Summary_2006_11_October.pdf
Okundu: Summary_2006_12_November.pdf
Okundu: Summary_2006_13_December.pdf
Okundu: Summary_2007_1_January.pdf
Okundu: Summary_2007_2_February.pdf
Okundu: Summary_2007_3_March.pdf
Okundu: Summary_2007_4_April.pdf
Okundu: Summary_2007_5_May.pdf
Okundu: Summary_2007_6_June.pdf
Okundu: Summary_2007_7_July.pdf
Okundu: Summary_2007_8_August.pdf
Okundu: Summary_2007_9_September.pdf
Okundu: Summary_2007_10_October.pdf
Okundu: Summary_2007_11_November.pdf
Okundu: Summary_2007_12_December.pdf
Okundu: Summary_2008_1_January.pdf
Okundu: Summary_2008_2_February.pdf
Okundu: Summary_2008_3_March.pdf
Okundu: Summary_2008_4_April.pdf
Okundu: Summary_2008_5_May.pdf
Okundu: Summary_2008_6_June.pdf
Okundu: Summary_2008_7_July.pdf
Okundu: Summary_2008_8_August.pdf
Okundu: Summary_2008_9_September.pdf
Okundu: Summary_2008_10_October.pdf
Okundu: Summary_2008_11_November.pdf
Okundu: Summary_2008_12_December.pdf
Okundu: Summary_2009_1_January.pdf
Okundu: Summary_2009_2_February.pdf
Okundu: Summary_2009_3_March.pdf
Okundu: Summary_2009_4_April.pdf
Okundu: Summary_2009_5_May.pdf
Okundu: Summary_2009_6_June.pdf
Okundu: Summary_2009_7_July.pdf
Okundu: Summary_2009_8_August.pdf
Okundu: Summary_2009_9_September.pdf
Okundu: Summary_2009_10_October.pdf
Okundu: Summary_2009_11_November.pdf
Okundu: Summary_2009_12_December.pdf
Okundu: Summary_2010_1_January.pdf
Okundu: Summary_2010_2_February.pdf
Okundu: Summary_2010_3_March.pdf
Okundu: Summary_2010_4_April.pdf
Okundu: Summary_2010_5_May.pdf
Okundu: Summary_2010_6_June.pdf
Okundu: Summary_2010_7_July.pdf
Okundu: Summary_2010_8_August.pdf
Okundu: Summary_2010_9_September.pdf
Okundu: Summary_2010_10_October.pdf
Okundu: Summary_2010_11_November.pdf
Okundu: Summary_2010_12_December.pdf
Okundu: Summary_2011_1_January.pdf
Okundu: Summary_2011_2_February.pdf
Okundu: Summary_2011_3_March.pdf
Okundu: Summary_2011_4_April.pdf
Okundu: Summary_2011_5_May.pdf
Okundu: Summary_2011_6_June.pdf
Okundu: Summary_2011_7_July.pdf
Okundu: Summary_2011_8_August.pdf
Okundu: Summary_2011_9_August.pdf
Okundu: Summary_2011_10_September.pdf
Okundu: Summary_2011_11_October.pdf
Okundu: Summary_2011_12_November.pdf
Okundu: Summary_2011_13_December.pdf
Okundu: Summary_2012_1_January.pdf
Okundu: Summary_2012_2_February.pdf
Okundu: Summary_2012_3_March.pdf
Okundu: Summary_2012_4_April.pdf
Okundu: Summary_2012_5_May.pdf
Okundu: Summary_2012_6_June.pdf
Okundu: Summary_2012_7_July.pdf
Okundu: Summary_2012_8_August.pdf
Okundu: Summary_2012_9_September.pdf
Okundu: Summary_2012_10_October.pdf
Okundu: Summary_2012_11_November.pdf
Okundu: Summary_2012_12_December.pdf
Okundu: Summary_2013_1_January.pdf
Okundu: Summary_2013_2_February.pdf
Okundu: Summary_2013_3_March.pdf
Okundu: Summary_2013_4_April.pdf
Okundu: Summary_2013_5_May.pdf
Okundu: Summary_2013_6_June.pdf
Okundu: Summary_2013_7_July.pdf
Okundu: Summary_2013_8_August.pdf
Okundu: Summary_2013_9_September.pdf
Okundu: Summary_2013_10_October.pdf
Okundu: Summary_2013_11_November.pdf
Okundu: Summary_2013_12_December.pdf
Okundu: Summary_2014_1_December.pdf
Okundu: Summary_2014_2_November.pdf
Okundu: Summary_2014_3_October.pdf
Okundu: Summary_2014_4_September.pdf
Okundu: Summary_2014_5_August.pdf
Okundu: Summary_2014_6_July.pdf
Okundu: Summary_2014_7_June.pdf
Okundu: Summary_2014_8_May.pdf
Okundu: Summary_2014_9_April.pdf
Okundu: Summary_2014_10_March.pdf
Okundu: Summary_2014_11_February.pdf
Okundu: Summary_2014_12_January.pdf
Okundu: Summary_2014_13_January.pdf
Okundu: Summary_2015_1_January.pdf
Okundu: Summary_2015_2_February.pdf
Okundu: Summary_2015_3_March.pdf
Okundu: Summary_2015_4_April.pdf
Okundu: Summary_2015_5_May.pdf
Okundu: Summary_2015_6_June.pdf
Okundu: Summary_2015_7_July.pdf
Okundu: Summary_2015_8_August.pdf
Okundu: Summary_2015_9_September.pdf
Okundu: Summary_2015_10_October.pdf
Okundu: Summary_2015_11_November.pdf
Okundu: Summary_2015_12_December.pdf
Okundu: Summary_2016_1_January.pdf
Okundu: Summary_2016_2_February.pdf
Okundu: Summary_2016_3_March.pdf
Okundu: Summary_2016_4_April.pdf
Okundu: Summary_2016_5_May.pdf
Okundu: Summary_2016_6_June.pdf
Okundu: Summary_2016_7_July.pdf
Okundu: Summary_2016_8_August.pdf
Okundu: Summary_2016_9_September.pdf
Okundu: Summary_2016_10_October.pdf
Okundu: Summary_2016_11_November.pdf
Okundu: Summary_2016_12_December.pdf
Okundu: Summary_2017_1_January.pdf
Okundu: Summary_2017_2_March.pdf
Okundu: Summary_2017_3_April.pdf
Okundu: Summary_2017_4_June.pdf
Okundu: Summary_2017_5_July.pdf
Okundu: Summary_2017_6_September.pdf
Okundu: Summary_2017_7_October.pdf
Okundu: Summary_2017_8_December.pdf
Okundu: Summary_2018_1_January.pdf
Okundu: Summary_2018_2_March.pdf
Okundu: Summary_2018_3_April.pdf
Okundu: Summary_2018_4_May.pdf
Okundu: Summary_2018_5_June.pdf
Okundu: Summary_2018_6_July.pdf
Okundu: Summary_2018_7_September.pdf
Okundu: Summary_2018_8_October.pdf
Okundu: Summary_2018_9_December.pdf
Okundu: Summary_2019_1_January.pdf
Okundu: Summary_2019_2_March.pdf
Okundu: Summary_2019_3_April.pdf
Okundu: Summary_2019_4_June.pdf
Okundu: Summary_2019_5_July.pdf
Okundu: Summary_2019_6_September.pdf
Okundu: Summary_2019_7_October.pdf
Okundu: Summary_2019_8_December.pdf
Okundu: Summary_2020_1_January.pdf
Okundu: Summary_2020_2_February.pdf
Okundu: Summary_2020_3_March.pdf
Okundu: Summary_2020_4_April.pdf
Okundu: Summary_2020_5_May.pdf
Okundu: Summary_2020_6_June.pdf
Okundu: Summary_2020_7_July.pdf
Okundu: Summary_2020_8_August.pdf
Okundu: Summary_2020_9_September.pdf
Okundu: Summary_2020_10_October.pdf
Okundu: Summary_2020_11_November.pdf
Okundu: Summary_2020_12_December.pdf
Okundu: Summary_2021_1_January.pdf
Okundu: Summary_2021_2_February.pdf
Okundu: Summary_2021_3_March.pdf
Okundu: Summary_2021_4_April.pdf
Okundu: Summary_2021_5_May.pdf
Okundu: Summary_2021_6_June.pdf
Okundu: Summary_2021_7_July.pdf
Okundu: Summary_2021_8_August.pdf
Okundu: Summary_2021_9_September.pdf
Okundu: Summary_2022_1_January.pdf
Okundu: Summary_2022_2_February.pdf
Okundu: Summary_2022_3_March.pdf
Okundu: Summary_2022_4_April.pdf
Okundu: Summary_2022_5_May.pdf
Okundu: Summary_2022_6_June.pdf
Okundu: Summary_2022_7_July.pdf
Okundu: Summary_2022_8_August.pdf
Okundu: Summary_2022_9_September.pdf
Okundu: Summary_2022_10_October.pdf
Okundu: Summary_2022_11_November.pdf
Okundu: Summary_2022_12_December.pdf
Okundu: Summary_2023_1_January.pdf
Okundu: Summary_2023_2_February.pdf
Okundu: Summary_2023_3_March.pdf
Okundu: Summary_2023_4_April.pdf
Okundu: Summary_2023_5_May.pdf
Okundu: Summary_2023_6_June.pdf
Okundu: Summary_2023_7_July.pdf
Okundu: Summary_2023_8_August.pdf
Okundu: Summary_2023_9_September.pdf
Okundu: Summary_2023_10_October.pdf
Okundu: Summary_2023_11_November.pdf
Okundu: Summary_2023_12_December.pdf
Okundu: Summary_2024_1_January.pdf
Okundu: Summary_2024_2_February.pdf
Okundu: Summary_2024_3_March.pdf
Okundu: Summary_2024_4_April.pdf
Okundu: Summary_2024_5_May.pdf
Okundu: Summary_2024_6_June.pdf
Okundu: Summary_2024_7_July.pdf
Okundu: Summary_2024_8_August.pdf
Okundu: Summary_2024_9_September.pdf
Okundu: Summary_2024_10_October.pdf
Okundu: Summary_2024_11_November.pdf
Okundu: Summary_2024_12_December.pdf
Okundu: Summary_2025_1_January.pdf
Okundu: Summary_2025_2_March.pdf
Okundu: Summary_2025_3_March.pdf
Okundu: Summary_2025_4_April.pdf
Okundu: Summary_2025_5_June.pdf
Okundu: Summary_2025_6_July.pdf
Okundu: Summary_2025_7_September.pdf
Okundu: Summary_2025_8_October.pdf
Okundu: Summary_2025_9_December.pdf

Bütün işlemler tamamlandı! Dosya konumu: Tum_Raporlar.txt

In [6]:
df.head(5)

,ReportName,Text
0,Summary_2006_1_January.pdf,No: 2006-6\n27 January 2006\nSUMMARY OF THE MO...
1,Summary_2006_2_February.pdf,Number: 2006- 10 7 March 2006\nSUMMARY OF THE ...
2,Summary_2006_3_March.pdf,"No: 2006-15\nMarch 31, 2006\nSUMMARY OF THE MO..."
3,Summary_2006_4_April.pdf,"No: 2006-21\nMay 04, 2006\nSUMMARY OF THE MONE..."
4,Summary_2006_5_May.pdf,"No: 2006-24\nJune 02, 2006\nSUMMARY OF THE MON..."

In [7]:
import nltk
import re

nltk.download('punkt')

SentenceDf = pd.DataFrame(columns = ["ReportName", "Sentences"])

def sentences_from_file(df):

    with open("titles.txt", "r", encoding="utf-8") as f:
        titles = [line.strip() for line in f if line.strip()]
    index = 0
    
    for row in df.index:

        reportname = df.loc[row, "ReportName"]
        full_text = df.loc[row, "Text"]
        clean_text = full_text.replace('\n', ' ')
        for title in titles:
            clean_text = clean_text.replace(title, ".")
        sentences = nltk.sent_tokenize(clean_text)
        
        for sentence in sentences:
            if any(item in sentence for item in titles) or len(sentence) <22 or sentence[:3] == "No:" or "SUMMARY OF THE MONETARY POLICY MEETING" in sentence or "cid:3" in sentence or "Meeting Date:" in sentence or re.match(r"^\d+\s", sentence) :
                continue

            sentence = re.sub(r"^\d+\.\s*", "", sentence)
            sentence = re.sub(r"^\d+\s+(?=[A-Z])", "", sentence)
            SentenceDf.loc[index] = [reportname, sentence]
            index+=1

    print(f"Başarılı! Toplam {index} cümle kaydedildi.")
        
sentences_from_file(df)

SentenceDf.to_excel("1_SummaryReportsV2.xlsx")

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\muham\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

Başarılı! Toplam 19167 cümle kaydedildi.

In [8]:
SentenceDf.head()

,ReportName,Sentences
0,Summary_2006_1_January.pdf,"In December, significant increases in the pric..."
1,Summary_2006_1_January.pdf,"On the other hand, fruit and vegetable prices,..."
2,Summary_2006_1_January.pdf,"With 7.72 percent, annual inflation was realiz..."
3,Summary_2006_1_January.pdf,"VAT cuts made in food, health and education se..."
4,Summary_2006_1_January.pdf,Even if the downward course in the inflation t...

In [9]:
len(SentenceDf)

19167

In [10]:
summary = (
    SentenceDf
    .groupby("Sentences")
    .agg(
        count=("ReportName", "size"),
        reports=("ReportName", lambda s: sorted(set(s)))
    )
    .reset_index()
    .sort_values("count", ascending=False)
)

summary[summary["count"] > 9].head(3)

summary.to_excel("1_RepeatedSentences.xlsx")

In [11]:
SentenceDf2 = SentenceDf.drop_duplicates(subset="Sentences")
SentenceDf2.to_excel("1_SummaryReportsV3.xlsx")
print(len(SentenceDf2))

16817

In [12]:
SentenceDf2.head(3)

,ReportName,Sentences
0,Summary_2006_1_January.pdf,"In December, significant increases in the pric..."
1,Summary_2006_1_January.pdf,"On the other hand, fruit and vegetable prices,..."
2,Summary_2006_1_January.pdf,"With 7.72 percent, annual inflation was realiz..."

In [13]:
with open("1_SummaryReportsV3.txt", "w", encoding="utf-8") as f:
    f.write("\n".join(SentenceDf2["Sentences"].astype(str)))