In [1]:
import pdfplumber
import os
import pandas as pd
import re

In [2]:
def year_month_key(filename):
    year, month = map(int, re.search(r"Decision_(\d+)_(\d+)_", filename).groups())
    return year, month

def merge_pdfs_to_single_txt(source_folder, output_txt_name):

    file_names = [x for x in os.listdir("Reports") if x.startswith("Decision_")]
    file_names = sorted(file_names, key=year_month_key)

    global df 

    df = pd.DataFrame(columns = ["ReportName", "Text"])
    index = 0

    for file_name in file_names:
        pdf_path = os.path.join(source_folder, file_name)
        
        try:
            with pdfplumber.open(pdf_path) as pdf:
                file_content = []
                for page in pdf.pages:
                    text = page.extract_text()
                    if text:
                        file_content.append(text)
                single_doc_text = "\n".join(file_content)
                single_doc_text = single_doc_text.replace("\n", " ")
                start_index = single_doc_text.index("The Monetary Policy Committee")
                df.loc[index] = [file_name, single_doc_text[start_index:]]
                index+=1
                print(f"Okundu: {file_name}")
                
        except Exception as e:
            print(f"Hata oluştu ({file_name}): {e}")

    df.to_excel("1_DecisionReportsV1.xlsx")
    print(f"\nBütün işlemler tamamlandı! Dosya konumu: {output_txt_name}")

merge_pdfs_to_single_txt("Reports", "Tum_Raporlar.txt")

Okundu: Decision_2006_1_January.pdf
Okundu: Decision_2006_2_February.pdf
Okundu: Decision_2006_3_March.pdf
Okundu: Decision_2006_4_April.pdf
Okundu: Decision_2006_5_May.pdf
Okundu: Decision_2006_6_June.pdf
Okundu: Decision_2006_7_June.pdf
Okundu: Decision_2006_8_July.pdf
Okundu: Decision_2006_9_August.pdf
Okundu: Decision_2006_10_September.pdf
Okundu: Decision_2006_11_October.pdf
Okundu: Decision_2006_12_November.pdf
Okundu: Decision_2006_13_December.pdf
Okundu: Decision_2007_1_January.pdf
Okundu: Decision_2007_2_February.pdf
Okundu: Decision_2007_3_March.pdf
Okundu: Decision_2007_4_April.pdf
Okundu: Decision_2007_5_May.pdf
Okundu: Decision_2007_6_June.pdf
Okundu: Decision_2007_7_July.pdf
Okundu: Decision_2007_8_August.pdf
Okundu: Decision_2007_9_September.pdf
Okundu: Decision_2007_10_October.pdf
Okundu: Decision_2007_11_November.pdf
Okundu: Decision_2007_12_December.pdf
Okundu: Decision_2008_1_January.pdf
Okundu: Decision_2008_2_February.pdf
Okundu: Decision_2008_3_March.pdf
Okundu: Decision_2008_4_April.pdf
Okundu: Decision_2008_5_May.pdf
Okundu: Decision_2008_6_June.pdf
Okundu: Decision_2008_7_July.pdf
Okundu: Decision_2008_8_August.pdf
Okundu: Decision_2008_9_September.pdf
Okundu: Decision_2008_10_October.pdf
Okundu: Decision_2008_11_November.pdf
Okundu: Decision_2008_12_December.pdf
Okundu: Decision_2009_1_January.pdf
Okundu: Decision_2009_2_February.pdf
Okundu: Decision_2009_3_March.pdf
Okundu: Decision_2009_4_April.pdf
Okundu: Decision_2009_5_May.pdf
Okundu: Decision_2009_6_June.pdf
Okundu: Decision_2009_7_July.pdf
Okundu: Decision_2009_8_August.pdf
Okundu: Decision_2009_9_September.pdf
Okundu: Decision_2009_10_October.pdf
Okundu: Decision_2009_11_November.pdf
Okundu: Decision_2009_12_December.pdf
Okundu: Decision_2010_1_January.pdf
Okundu: Decision_2010_2_February.pdf
Okundu: Decision_2010_3_March.pdf
Okundu: Decision_2010_4_April.pdf
Okundu: Decision_2010_5_May.pdf
Okundu: Decision_2010_6_June.pdf
Okundu: Decision_2010_7_July.pdf
Okundu: Decision_2010_8_August.pdf
Okundu: Decision_2010_9_September.pdf
Okundu: Decision_2010_10_October.pdf
Okundu: Decision_2010_11_November.pdf
Okundu: Decision_2010_12_December.pdf
Okundu: Decision_2011_1_January.pdf
Okundu: Decision_2011_2_February.pdf
Okundu: Decision_2011_3_March.pdf
Okundu: Decision_2011_4_April.pdf
Okundu: Decision_2011_5_May.pdf
Okundu: Decision_2011_6_June.pdf
Okundu: Decision_2011_7_July.pdf
Okundu: Decision_2011_8_August.pdf
Okundu: Decision_2011_9_August.pdf
Okundu: Decision_2011_10_September.pdf
Okundu: Decision_2011_11_October.pdf
Okundu: Decision_2011_12_November.pdf
Okundu: Decision_2011_13_December.pdf
Okundu: Decision_2012_1_January.pdf
Okundu: Decision_2012_2_February.pdf
Okundu: Decision_2012_3_March.pdf
Okundu: Decision_2012_4_April.pdf
Okundu: Decision_2012_5_May.pdf
Okundu: Decision_2012_6_June.pdf
Okundu: Decision_2012_7_July.pdf
Okundu: Decision_2012_8_August.pdf
Okundu: Decision_2012_9_September.pdf
Okundu: Decision_2012_10_October.pdf
Okundu: Decision_2012_11_November.pdf
Okundu: Decision_2012_12_December.pdf
Okundu: Decision_2013_1_January.pdf
Okundu: Decision_2013_2_February.pdf
Okundu: Decision_2013_3_March.pdf
Okundu: Decision_2013_4_April.pdf
Okundu: Decision_2013_5_May.pdf
Okundu: Decision_2013_6_June.pdf
Okundu: Decision_2013_7_July.pdf
Okundu: Decision_2013_8_August.pdf
Okundu: Decision_2013_9_September.pdf
Okundu: Decision_2013_10_October.pdf
Okundu: Decision_2013_11_November.pdf
Okundu: Decision_2013_12_December.pdf
Okundu: Decision_2014_1_January.pdf
Okundu: Decision_2014_2_January.pdf
Okundu: Decision_2014_3_February.pdf
Okundu: Decision_2014_4_March.pdf
Okundu: Decision_2014_5_April.pdf
Okundu: Decision_2014_6_May.pdf
Okundu: Decision_2014_7_June.pdf
Okundu: Decision_2014_8_July.pdf
Okundu: Decision_2014_9_August.pdf
Okundu: Decision_2014_10_September.pdf
Okundu: Decision_2014_11_October.pdf
Okundu: Decision_2014_12_November.pdf
Okundu: Decision_2014_13_December.pdf
Okundu: Decision_2015_1_January.pdf
Okundu: Decision_2015_2_February.pdf
Okundu: Decision_2015_3_March.pdf
Okundu: Decision_2015_4_April.pdf
Okundu: Decision_2015_5_May.pdf
Okundu: Decision_2015_6_June.pdf
Okundu: Decision_2015_7_July.pdf
Okundu: Decision_2015_8_August.pdf
Okundu: Decision_2015_9_September.pdf
Okundu: Decision_2015_10_October.pdf
Okundu: Decision_2015_11_November.pdf
Okundu: Decision_2015_12_December.pdf
Okundu: Decision_2016_1_January.pdf
Okundu: Decision_2016_2_February.pdf
Okundu: Decision_2016_3_March.pdf
Okundu: Decision_2016_4_April.pdf
Okundu: Decision_2016_5_May.pdf
Okundu: Decision_2016_6_June.pdf
Okundu: Decision_2016_7_July.pdf
Okundu: Decision_2016_8_August.pdf
Okundu: Decision_2016_9_September.pdf
Okundu: Decision_2016_10_October.pdf
Okundu: Decision_2016_11_November.pdf
Okundu: Decision_2016_12_December.pdf
Okundu: Decision_2017_1_January.pdf
Okundu: Decision_2017_2_March.pdf
Okundu: Decision_2017_3_April.pdf
Okundu: Decision_2017_4_June.pdf
Okundu: Decision_2017_5_July.pdf
Okundu: Decision_2017_6_September.pdf
Okundu: Decision_2017_7_October.pdf
Okundu: Decision_2017_8_December.pdf
Okundu: Decision_2018_1_January.pdf
Okundu: Decision_2018_2_March.pdf
Okundu: Decision_2018_3_April.pdf
Okundu: Decision_2018_4_May.pdf
Okundu: Decision_2018_5_June.pdf
Okundu: Decision_2018_6_July.pdf
Okundu: Decision_2018_7_September.pdf
Okundu: Decision_2018_8_October.pdf
Okundu: Decision_2018_9_December.pdf
Okundu: Decision_2019_1_January.pdf
Okundu: Decision_2019_2_March.pdf
Okundu: Decision_2019_3_April.pdf
Okundu: Decision_2019_4_June.pdf
Okundu: Decision_2019_5_July.pdf
Okundu: Decision_2019_6_September.pdf
Okundu: Decision_2019_7_October.pdf
Okundu: Decision_2019_8_December.pdf
Okundu: Decision_2020_1_January.pdf
Okundu: Decision_2020_2_February.pdf
Okundu: Decision_2020_3_March.pdf
Okundu: Decision_2020_4_April.pdf
Okundu: Decision_2020_5_May.pdf
Okundu: Decision_2020_6_June.pdf
Okundu: Decision_2020_7_July.pdf
Okundu: Decision_2020_8_August.pdf
Okundu: Decision_2020_9_September.pdf
Okundu: Decision_2020_10_October.pdf
Okundu: Decision_2020_11_November.pdf
Okundu: Decision_2020_12_December.pdf
Okundu: Decision_2021_1_January.pdf
Okundu: Decision_2021_2_February.pdf
Okundu: Decision_2021_3_March.pdf
Okundu: Decision_2021_4_April.pdf
Okundu: Decision_2021_5_May.pdf
Okundu: Decision_2021_6_June.pdf
Okundu: Decision_2021_7_July.pdf
Okundu: Decision_2021_8_August.pdf
Okundu: Decision_2021_9_September.pdf
Okundu: Decision_2021_10_October.pdf
Okundu: Decision_2021_11_Novermber.pdf
Okundu: Decision_2021_12_December.pdf
Okundu: Decision_2022_1_January.pdf
Okundu: Decision_2022_2_February.pdf
Okundu: Decision_2022_3_March.pdf
Okundu: Decision_2022_4_April.pdf
Okundu: Decision_2022_5_May.pdf
Okundu: Decision_2022_6_June.pdf
Okundu: Decision_2022_7_July.pdf
Okundu: Decision_2022_8_August.pdf
Okundu: Decision_2022_9_September.pdf
Okundu: Decision_2022_10_October.pdf
Okundu: Decision_2022_11_November.pdf
Okundu: Decision_2022_12_December.pdf
Okundu: Decision_2023_1_January.pdf
Okundu: Decision_2023_2_February.pdf
Okundu: Decision_2023_3_March.pdf
Okundu: Decision_2023_4_April.pdf
Okundu: Decision_2023_5_May.pdf
Okundu: Decision_2023_6_June.pdf
Okundu: Decision_2023_7_July.pdf
Okundu: Decision_2023_8_August.pdf
Okundu: Decision_2023_9_September.pdf
Okundu: Decision_2023_10_October.pdf
Okundu: Decision_2023_11_November.pdf
Okundu: Decision_2023_12_December.pdf
Okundu: Decision_2024_1_January.pdf
Okundu: Decision_2024_2_February.pdf
Okundu: Decision_2024_3_March.pdf
Okundu: Decision_2024_4_April.pdf
Okundu: Decision_2024_5_May.pdf
Okundu: Decision_2024_6_June.pdf
Okundu: Decision_2024_7_July.pdf
Okundu: Decision_2024_8_August.pdf
Okundu: Decision_2024_9_September.pdf
Okundu: Decision_2024_10_October.pdf
Okundu: Decision_2024_11_November.pdf
Okundu: Decision_2024_12_December.pdf
Okundu: Decision_2025_1_January.pdf
Okundu: Decision_2025_2_March.pdf
Okundu: Decision_2025_3_March.pdf
Okundu: Decision_2025_4_April.pdf
Okundu: Decision_2025_5_June.pdf
Okundu: Decision_2025_6_July.pdf
Okundu: Decision_2025_7_September.pdf
Okundu: Decision_2025_8_October.pdf
Okundu: Decision_2025_9_December.pdf

Bütün işlemler tamamlandı! Dosya konumu: Tum_Raporlar.txt

In [3]:
df = pd.read_excel("1_DecisionReportsV1.xlsx", index_col="Unnamed: 0")
df.head()

,ReportName,Text
0,Decision_2006_1_January.pdf,The Monetary Policy Committee has concluded th...
1,Decision_2006_2_February.pdf,The Monetary Policy Committee has decided to k...
2,Decision_2006_3_March.pdf,The Monetary Policy Committee has decided to k...
3,Decision_2006_4_April.pdf,The Monetary Policy Committee has decided to c...
4,Decision_2006_5_May.pdf,The Monetary Policy Committee has decided to k...

In [4]:
import nltk
import re

nltk.download('punkt')

SentenceDf = pd.DataFrame(columns = ["ReportName", "Sentences"])

def sentences_from_file(df):


    index = 0
    
    for row in df.index:

        reportname = df.loc[row, "ReportName"]
        full_text = df.loc[row, "Text"]
        sentences = nltk.sent_tokenize(full_text)
        
        for sentence in sentences:
            if len(sentence) < 20:
                continue
            SentenceDf.loc[index] = [reportname, sentence]
            index+=1

    print(f"Başarılı! Toplam {index} cümle kaydedildi.")
        
sentences_from_file(df)

SentenceDf.to_excel("1_DecisionReportsFinalDataset.xlsx")

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\muham\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

Başarılı! Toplam 3474 cümle kaydedildi.

In [5]:
SentenceDf.head()

,ReportName,Sentences
0,Decision_2006_1_January.pdf,The Monetary Policy Committee has concluded th...
1,Decision_2006_1_January.pdf,It is estimated that although the downward tre...
2,Decision_2006_1_January.pdf,"Despite this downward trend, in the light of c..."
3,Decision_2006_1_January.pdf,The major reasons behind this argument are the...
4,Decision_2006_1_January.pdf,"As a result, it has been decided to keep the s..."

In [6]:
summary = (
    SentenceDf
    .groupby("Sentences")
    .agg(
        count=("ReportName", "size"),
        reports=("ReportName", lambda s: sorted(set(s)))
    )
    .reset_index()
    .sort_values("count", ascending=False)
)

summary[summary["count"] > 9].head(3)
summary.to_excel("1_RepeatedSentences.xlsx")

In [7]:
# with open("1_SummaryReportsV3.txt", "w", encoding="utf-8") as f:
#     f.write("\n".join(SentenceDf2["Sentences"].astype(str)))